language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t 1608996/docker-test -f Dockerfile.dev .

script:
    - docker run -e CI=true 1608996/docker-test npm run test