language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t 1608996/docker-practice -f Dockerfile.dev .

script:
    - docker run -e CI=true 1608996/docker-practice npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    name: "docker-practice"
    env: "DockerPractice-env"
    bucket_name: "elasticbeanstalk-us-east-2-985767508874"
    bucket_path: "docker-practice"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY